### ISSUE TITLE
La zone texte n'est plus éditable

### ISSUE THREAD

**Issue by Bekik** [simonvdfr/Translucide#71]
Bonjour, 

Je rencontre un problème que je n'avais pas avant sur mon site. 
Les zones de texte ne sont plus éditables alors que je n'ai pas de soucis avec les titres.
J'ai mis à jour le dossier "api" et je suis passée en PHP 8.2 mais le problème persiste.

Merci de m'éclairer.

**Comment by simonvdfr** [comment]
Avez-vous essayé dans un navigateur privé avec tous les plugins désactivés ? Visiblement un plugin comme LanguageTools crée des problèmes dans les zones de textes éditables.
Sinon, vous avez des erreurs javascript dans la console de développeurs (F12) ?
Tout est bien chargé dans les Network de la console de développeurs ?

**Comment by Bekik** [comment]
Je viens d'essayer dans le navigateur privé et cela fonctionne correctement.

Sinon au niveau de la console sans passer par le navigateur privé j'ai 15 problèmes sous chrome. Sous microsoft edge j'en ai aussi mais moins.
Je vais essayer en désactivant des extensions.

Erreurs de la console :

Failed to load resource: the server responded with a status of 404 ()
 0.016219854354858
chrome-extension://invalid/:1 
        
        
       Failed to load resource: net::ERR_FAILED
impression.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plumetika.com/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
37Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
plumetika.com/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
inlineForm.html:13 Unchecked runtime.lastError: You do not have a background page.
64[Deprecation] Listener added for a 'DOMNodeInserted' mutation event. This event type is deprecated, and will be removed from this browser VERY soon. Usage of this event listener will cause performance issues today, and represents a large risk of imminent site breakage. Consider using MutationObserver instead. See <URL> for more information.
4content.js:5564 undefined
styles.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
impression.css:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plumetika.com/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
plumetika.com/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
36Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (<URL>)
    at e.handleMessage (<URL>)
    at <URL>
    at <URL>
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
inlineForm.html:1 Error in event handler: Error: invalid arguments to extensionAdapter.sendMessageToTab
    at e.sendMessageToTab (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:65501)
    at e.handleMessage (chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:106817)
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:103083
    at chrome-extension://caljgklbbfbcjjanaijlacgncafpegll/js/content/app/inlineForm/index.js:80:78040
plumetika.com/:1 Error handling response: Error: runtime/sendMessage: The message port closed before a response was received.
    at chrome-extension://fdjamakpfbbddfjaooikfcpapjohcfmg/content/contentScripts/kwift.CHROME.js:1:336018
plumetika.com/:1 Error handling response: Error: runtime/sendMessage: The message port closed before a response was received.
    at chrome-extension://fdjamakpfbbddfjaooikfcpapjohcfmg/content/contentScripts/kwift.CHROME.js:1:336018
plumetika.com/:1 Error handling response: Error: runtime/sendMessage: The message port closed before a response was received.
    at chrome-extension://fdjamakpfbbddfjaooikfcpapjohcfmg/content/contentScripts/kwift.CHROME.js:1:336018
